Extraccion de USA RE a Mongo

In [4]:
import pandas as pd
import polars as pl
import time
import requests
from pymongo import MongoClient
from pprint import pprint
import psycopg
from pathlib import Path
import pandas as pd
from sqlalchemy import create_engine
import io

In [ ]:

API = "https://data.ct.gov/resource/5mzw-sjtu.json"
CHUNK = 50000

client = MongoClient("mongodb+srv://RealEstateMan:Nb2rf5qwI0df9c6V@realestatecluster.cqx7s32.mongodb.net/?appName=RealEstateCluster")
col = client.RealState.realestate_raw

offset = 0
#alkdflkajdsfjasdfjaklsdfj
while True:
    params = {"$limit": CHUNK, "$offset": offset}
    r = requests.get(API, params=params, timeout=60)
    r.raise_for_status()
    rows = r.json()

    if len(rows) == 0:
        break
    
    col.insert_many(rows)

    offset += CHUNK
    time.sleep(0.2)

print("Total documentos(rows):", col.count_documents({}))

OperationFailure: you are over your space quota, using 515 MB of 512 MB, full error: {'ok': 0, 'errmsg': 'you are over your space quota, using 515 MB of 512 MB', 'code': 8000, 'codeName': 'AtlasError'}

# Conexión Mongos y descarga de Datos

In [1]:
from pymongo import MongoClient

uri = "mongodb+srv://RealEstateMan:Nb2rf5qwI0df9c6V@realestatecluster.cqx7s32.mongodb.net/?appName=RealEstateCluster"
client = MongoClient(uri)
col = client["RealState"]["realestate_raw"]

print("OK. docs:", col.count_documents({}))

OK. docs: 1391722

In [2]:
def load_data():
    df = pd.DataFrame(list(col.find()))
    df['_id'] = df['_id'].astype(str)
    pl_df = pl.from_pandas(df)
    return pl_df

In [5]:
pl_df = load_data()

# Transformación básica de variables

Transformaciones

1. Eliminar Columnas
2. Conversion a int y float
3. Datarecorded a fechas
4. Long Lat a coordinadas
5. Strip chars de valores

In [6]:
# Inspección rápida de pl_df
print("=" * 50)
print("INSPECCIÓN RÁPIDA DEL DATAFRAME")
print("=" * 50)
print(f"\nForma: {pl_df.shape} (filas, columnas)")
print(f"\nColumnas: {pl_df.columns}")
print(f"\nEsquema (tipos):")
print(pl_df.schema)
print(f"\nPrimeras 5 filas:")
print(pl_df.head())
print(f"\nEstadísticas básicas:")
print(pl_df.describe())

==================================================
INSPECCIÓN RÁPIDA DEL DATAFRAME
==================================================

Forma: (1391722, 19) (filas, columnas)

Columnas: ['_id', 'serialnumber', 'listyear', 'daterecorded', 'town', 'address', 'assessedvalue', 'saleamount', 'salesratio', 'propertytype', 'residentialtype', 'geo_coordinates', ':@computed_region_dam5_q64j', ':@computed_region_nhmp_cq6b', ':@computed_region_m4y2_whse', ':@computed_region_snd5_k6zv', 'remarks', 'nonusecode', 'opm_remarks']

Esquema (tipos):
Schema({'_id': String, 'serialnumber': String, 'listyear': String, 'daterecorded': String, 'town': String, 'address': String, 'assessedvalue': String, 'saleamount': String, 'salesratio': String, 'propertytype': String, 'residentialtype': String, 'geo_coordinates': Struct({'coordinates': List(Float64), 'type': String}), ':@computed_region_dam5_q64j': String, ':@computed_region_nhmp_cq6b': String, ':@computed_region_m4y2_whse': String, ':@computed_region_snd5_k6zv': String, 'remarks': String, 'nonusecode': String, 'opm_remarks': String})

Primeras 5 filas:
shape: (5, 19)
┌────────────┬────────────┬──────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ _id        ┆ serialnumb ┆ listyear ┆ daterecor ┆ … ┆ :@compute ┆ remarks ┆ nonusecod ┆ opm_remar │
│ ---        ┆ er         ┆ ---      ┆ ded       ┆   ┆ d_region_ ┆ ---     ┆ e         ┆ ks        │
│ str        ┆ ---        ┆ str      ┆ ---       ┆   ┆ snd5_k6zv ┆ str     ┆ ---       ┆ ---       │
│            ┆ str        ┆          ┆ str       ┆   ┆ ---       ┆         ┆ str       ┆ str       │
│            ┆            ┆          ┆           ┆   ┆ str       ┆         ┆           ┆           │
╞════════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ 698f65aabb ┆ 2020177    ┆ 2020     ┆ 2021-04-1 ┆ … ┆ 4         ┆ null    ┆ null      ┆ null      │
│ 4a7e47c78a ┆            ┆          ┆ 4T00:00:0 ┆   ┆           ┆         ┆           ┆           │
│ 2035       ┆            ┆          ┆ 0.000     ┆   ┆           ┆         ┆           ┆           │
│ 698f65aabb ┆ 2020225    ┆ 2020     ┆ 2021-05-2 ┆ … ┆ null      ┆ null    ┆ null      ┆ null      │
│ 4a7e47c78a ┆            ┆          ┆ 6T00:00:0 ┆   ┆           ┆         ┆           ┆           │
│ 2036       ┆            ┆          ┆ 0.000     ┆   ┆           ┆         ┆           ┆           │
│ 698f65aabb ┆ 2020348    ┆ 2020     ┆ 2021-09-1 ┆ … ┆ null      ┆ null    ┆ null      ┆ null      │
│ 4a7e47c78a ┆            ┆          ┆ 3T00:00:0 ┆   ┆           ┆         ┆           ┆           │
│ 2037       ┆            ┆          ┆ 0.000     ┆   ┆           ┆         ┆           ┆           │
│ 698f65aabb ┆ 2020090    ┆ 2020     ┆ 2020-12-1 ┆ … ┆ null      ┆ null    ┆ null      ┆ null      │
│ 4a7e47c78a ┆            ┆          ┆ 4T00:00:0 ┆   ┆           ┆         ┆           ┆           │
│ 2038       ┆            ┆          ┆ 0.000     ┆   ┆           ┆         ┆           ┆           │
│ 698f65aabb ┆ 210288     ┆ 2021     ┆ 2022-06-2 ┆ … ┆ 1         ┆ null    ┆ null      ┆ null      │
│ 4a7e47c78a ┆            ┆          ┆ 0T00:00:0 ┆   ┆           ┆         ┆           ┆           │
│ 2039       ┆            ┆          ┆ 0.000     ┆   ┆           ┆         ┆           ┆           │
└────────────┴────────────┴──────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

Estadísticas básicas:
shape: (9, 20)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ _id       ┆ serialnum ┆ listyear ┆ … ┆ :@compute ┆ remarks   ┆ nonusecod ┆ opm_remar │
│ ---       ┆ ---       ┆ ber       ┆ ---      ┆   ┆ d_region_ ┆ ---       ┆ e         ┆ ks        │
│ str       ┆ str       ┆ ---       ┆ str      ┆   ┆ snd5_k6zv ┆ str       ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆          ┆   ┆ ---       ┆           ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆ str       ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 1391722   ┆ 1391722   ┆ 1391722  ┆ … ┆ 465160    ┆ 218010    ┆ 380853    ┆ 19656     │
│ null_coun ┆ 0         ┆ 0         ┆ 0        ┆ … ┆ 926562    ┆ 1173712   ┆ 1010869   ┆ 1372066   │
│ t         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ std       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ min       ┆ 698f65aab ┆ 0         ┆ 2001     ┆ … ┆ 1         ┆ "AS IS    ┆ 01 -      ┆ #190309   │
│           ┆ b4a7e47c7 ┆           ┆          ┆   ┆           ┆ SALE"     ┆ Family    ┆ HAS SAME  │
│           ┆ 8a2035    ┆           ┆          ┆   ┆           ┆           ┆           ┆ REMARK    │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ AND IS…   │
│ 25%       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ max       ┆ 69906c653 ┆ 99529     ┆ 2023     ┆ … ┆ 9         ┆ �non-mark ┆ Single    ┆ town site │
│           ┆ 7a6b9f973 ┆           ┆          ┆   ┆           ┆ et transa ┆ Family    ┆ shows ass │
│           ┆ c5ea9c    ┆           ┆          ┆   ┆           ┆ ction     ┆           ┆ essment   │
│           ┆           ┆           ┆          ┆   ┆           ┆ includ…   ┆           ┆ as …      │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
# Eliminar columnas específicas
columnas_a_eliminar = [
    ':@computed_region_dam5_q64j',
    ':@computed_region_nhmp_cq6b',
    ':@computed_region_m4y2_whse',
    ':@computed_region_snd5_k6zv'
]

# Eliminar las columnas
pl_df = pl_df.drop(columnas_a_eliminar)

print(f"Columnas eliminadas: {columnas_a_eliminar}")
print(f"\nDataFrame después de eliminar:")
print(f"Forma: {pl_df.shape}")
print(f"Columnas restantes ({len(pl_df.columns)})")

Columnas eliminadas: [':@computed_region_dam5_q64j', ':@computed_region_nhmp_cq6b', ':@computed_region_m4y2_whse', ':@computed_region_snd5_k6zv']

DataFrame después de eliminar:
Forma: (1391722, 15)
Columnas restantes (15)

In [8]:
# copia de pl_df a una limpia que se llame pl_clean
pl_clean = pl_df.clone()

In [9]:
# Conversiones obligatorias con Polars
pl_clean = pl_clean.with_columns([
    # Numéricos
    pl.col("listyear").cast(pl.Int64, strict=False),
    pl.col("assessedvalue").cast(pl.Float64, strict=False),
    pl.col("saleamount").cast(pl.Float64, strict=False),
    pl.col("salesratio").cast(pl.Float64, strict=False),
])

In [10]:
# inspeccionar daterecord para saber su formato
print("Ejemplo de daterecorded:")
print(pl_clean.select(pl.col("daterecorded")).head(10))

Ejemplo de daterecorded:
shape: (10, 1)
┌─────────────────────────┐
│ daterecorded            │
│ ---                     │
│ str                     │
╞═════════════════════════╡
│ 2021-04-14T00:00:00.000 │
│ 2021-05-26T00:00:00.000 │
│ 2021-09-13T00:00:00.000 │
│ 2020-12-14T00:00:00.000 │
│ 2022-06-20T00:00:00.000 │
│ 2021-09-07T00:00:00.000 │
│ 2020-12-15T00:00:00.000 │
│ 2021-06-01T00:00:00.000 │
│ 2021-01-25T00:00:00.000 │
│ 2020-11-13T00:00:00.000 │
└─────────────────────────┘

In [11]:
# conversion de daterecorded a formato fecha 
pl_clean = pl_clean.with_columns(
    pl.col("daterecorded")
      .str.strptime(pl.Datetime, strict=False)
      .dt.date()
      .alias("daterecorded")
)

In [12]:
# convertimos latitud y longitud
pl_clean = (
    pl_clean
    .with_columns([
        pl.col("geo_coordinates")
          .struct.field("coordinates")
          .list.get(0)
          .alias("longitude"),

        pl.col("geo_coordinates")
          .struct.field("coordinates")
          .list.get(1)
          .alias("latitude"),
    ])
    .drop("geo_coordinates")
)

In [13]:
#limpieza de datos categoricos
pl_clean = pl_clean.with_columns([
    pl.col("town")
      .str.strip_chars()
      .str.to_uppercase(),

    pl.col("address")
      .str.strip_chars()
      .str.to_uppercase(),

    pl.col("propertytype")
      .str.strip_chars(),

    pl.col("residentialtype")
      .str.strip_chars(),
])

# Normalización

In [14]:
pl_tablas = pl_clean.clone()

## Decisión de modelado: generación de claves y relaciones en la base de datos

En este proyecto se adopta una arquitectura donde el proceso ETL (realizado en Polars) se encarga exclusivamente de la limpieza, transformación y estructuración lógica de los datos, mientras que la definición formal del modelo relacional (claves primarias, claves foráneas y restricciones de integridad) se delega al sistema gestor de base de datos (por ejemplo, PostgreSQL).

**Esta decisión responde a varias buenas prácticas en ingeniería de datos:**

- Separación de responsabilidades:
El ETL prepara datos consistentes y normalizados; el motor relacional garantiza integridad referencial y reglas de negocio mediante constraints.

- Portabilidad y flexibilidad:
Al no generar claves surrogate en la capa de transformación, el pipeline permanece independiente del motor de base de datos. Esto facilita migraciones futuras (Postgres, MySQL, SQLite, etc.).

- Integridad referencial formal:
Los sistemas relacionales están diseñados para gestionar claves primarias (PK), claves foráneas (FK), índices y validaciones de forma robusta y eficiente.

- Mantenimiento y escalabilidad:
Delegar la generación de IDs (IDENTITY / SERIAL / AUTOINCREMENT) al motor evita dependencias en el orden de carga o en la estabilidad del dataset.

Por lo tanto, en esta etapa se construyen las tablas dimensionales y de hechos con sus atributos limpios y normalizados, dejando la definición de relaciones y restricciones para la fase de carga en la base de datos relacional.

### Dimensions

### Tabla TOWN

In [15]:
town_dim = (
    pl_tablas
    .select(
        pl.col("town").fill_null("UNKNOWN")
    )
    .unique()
    .sort("town")
)
town_dim

shape: (170, 1)
┌───────────────┐
│ town          │
│ ---           │
│ str           │
╞═══════════════╡
│ ***UNKNOWN*** │
│ ANDOVER       │
│ ANSONIA       │
│ ASHFORD       │
│ AVON          │
│ …             │
│ WINDSOR LOCKS │
│ WOLCOTT       │
│ WOODBRIDGE    │
│ WOODBURY      │
│ WOODSTOCK     │
└───────────────┘

### Tabla Property

In [16]:
property_dim = (
    pl_tablas
    .select([
        pl.col("town"),
        pl.col("address").fill_null("UNKNOWN"),
        pl.col("propertytype").fill_null("UNKNOWN"),
        pl.col("residentialtype").fill_null("UNKNOWN"),
        pl.col("latitude"),
        pl.col("longitude"),
    ])
    .unique()
    .sort(["town", "address"])
)


pprint(property_dim.schema)

Schema([('town', String),
        ('address', String),
        ('propertytype', String),
        ('residentialtype', String),
        ('latitude', Float64),
        ('longitude', Float64)])

### NO_USE_CODE

Non usable sale code typically means the sale price is not reliable for use in the determination of a property value. See attachments in the dataset description page for a listing of codes

In [17]:
non_use_code_dim = (
    pl_tablas
    .select(
        pl.col("nonusecode")
          .fill_null("UNKNOWN")
    )
    .unique()
    .sort("nonusecode")
)

non_use_code_dim.unique()

shape: (75, 1)
┌─────────────────────────┐
│ nonusecode              │
│ ---                     │
│ str                     │
╞═════════════════════════╡
│ 01 - Family             │
│ 02 - Love and Affection │
│ 03 - Inter Corporation  │
│ 04 - Correcting Deed    │
│ 05 - Deed Date          │
│ …                       │
│ 8                       │
│ 88                      │
│ 9                       │
│ Single Family           │
│ UNKNOWN                 │
└─────────────────────────┘

### Sale_notes

In [18]:
sale_notes = (
    pl_tablas
    .select([
        pl.col("serialnumber"),
        pl.col("remarks").fill_null("UNKNOWN"),
        pl.col("opm_remarks").fill_null("UNKNOWN"),
    ]))
  

sale_notes.schema

Schema([('serialnumber', String),
        ('remarks', String),
        ('opm_remarks', String)])

### SALES_FACT - TABLA DE HECHOS

Uso de variables “puente” en la fact table (justificación).
Para construir las relaciones entre SALES y las dimensiones (PROPERTY_DIM, TOWN, etc.) existen dos enfoques comunes: (1) crear una clave natural/hashy (por ejemplo property_key) para enlazar tablas con una sola columna, o (2) mantener en la fact los atributos necesarios como variables puente y resolver las claves sustitutas (surrogate keys) en la base relacional mediante joins multi-columna.

En este proyecto se elige el enfoque de variables puente porque el dataset contiene una proporción alta de valores faltantes que se estandarizan como "UNKNOWN". En este contexto, una clave hash basada en atributos puede introducir colisiones lógicas (distintas propiedades terminan compartiendo la misma combinación de atributos debido a campos "UNKNOWN" o coordenadas ausentes), provocando enlaces incorrectos entre la fact y la dimensión.

Mantener los atributos puente en la fact permite realizar la resolución de property_id en SQL de forma explícita, auditable y controlable, aplicando reglas adicionales si es necesario (por ejemplo, priorizar address cuando existe, tratar casos con lat/lon nulos, o separar registros con demasiados "UNKNOWN"). Además, este enfoque mantiene el ETL más agnóstico del motor de base de datos, dejando la generación de claves sustitutas y la integridad referencial para la capa relacional.

In [19]:
sales_fact = (
    pl_tablas
    .select([
        pl.col("serialnumber"),

        pl.col("listyear"),
        pl.col("daterecorded"),  
        pl.col("assessedvalue"),
        pl.col("saleamount"),
        pl.col("salesratio"),

        # Puente para resolver property_id en la DB (porque property_dim no lleva nonusecode)
        pl.col("town").fill_null("UNKNOWN"),
        pl.col("address").fill_null("UNKNOWN"),
        pl.col("propertytype").fill_null("UNKNOWN"),
        pl.col("residentialtype").fill_null("UNKNOWN"),
        pl.col("latitude"),
        pl.col("longitude"),

        # Puente para resolver nonusecode_id en la DB
        pl.col("nonusecode"),
    ])
)

sales_fact.schema

Schema([('serialnumber', String),
        ('listyear', Int64),
        ('daterecorded', Date),
        ('assessedvalue', Float64),
        ('saleamount', Float64),
        ('salesratio', Float64),
        ('town', String),
        ('address', String),
        ('propertytype', String),
        ('residentialtype', String),
        ('latitude', Float64),
        ('longitude', Float64),
        ('nonusecode', String)])

# LOAD

# CARGA A POSTGRES

## Conexión

import socket
socket.gethostbyname("db.bxelbfnsugczmcfgltwm.supabase.co")

In [ ]:
import os
from dotenv import load_dotenv, find_dotenv
from urllib.parse import urlparse
import psycopg2

env_path = find_dotenv(usecwd=True)
load_dotenv(env_path, override=True)

url = os.getenv("DATABASE_URL")
if not url:
    raise RuntimeError("Falta DATABASE_URL en .env")

p = urlparse(url)
print("Conectando a:", p.hostname, p.port)  # Debe ser aws-0-eu-west-1.pooler.supabase.com 5432 (o 6543)

# Conecta
conn = psycopg2.connect(url)  # sslmode=require ya va en la URL
cur = conn.cursor()
cur.execute("SELECT current_user, inet_server_addr(), inet_server_port(), now();")
user, ip, port, now = cur.fetchone()
print(f"OK: user={user} ip={ip} port={port} now={now}")

Conectando a: aws-1-eu-west-1.pooler.supabase.com 6543
OK: user=postgres ip=2a05:d018:135e:169a:fbc4:36b0:3b51:648 port=5432 now=2026-02-14 20:42:59.548496+00:00

Dim Town

In [84]:


df = town_dim.select("town").unique()

buf = io.StringIO() #Archivo "falso" creado en la RAM
df.write_csv(buf, include_header=False) #Convierte polars a csv y lo esribe en este archivo "falso"

buf.seek(0)
cur.copy_from(buf, 'tmp_town', columns=('town',), sep=',')

cur.execute("""
    INSERT INTO d_town (town)
    SELECT DISTINCT town
    FROM tmp_town
    WHERE town IS NOT NULL AND town <> ''
    ON CONFLICT (town) DO NOTHING;
""")


conn.commit()

cur.execute("SELECT COUNT(*) FROM d_town;")
print("Filas en d_town:", cur.fetchone()[0])

Filas en d_town: 170

dim non use code

In [85]:
import io
import polars as pl

df = non_use_code_dim.select("nonusecode")  # garantiza 1 columna con el nombre correcto

# 1) Crear tabla si no existe
cur.execute("""
    CREATE TABLE IF NOT EXISTS d_non_use_code (
        nonusecode_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        nonusecode    TEXT UNIQUE NOT NULL
    );
""")

# 2) CSV en memoria (sin header)
buf = io.StringIO()
df.write_csv(buf, include_header=False)
buf.seek(0)

# 3) Temp table
cur.execute("DROP TABLE IF EXISTS tmp_non_use_code;")
cur.execute("CREATE TEMP TABLE tmp_non_use_code (nonusecode TEXT) ON COMMIT DROP;")

# 4) COPY con psycopg2
cur.copy_from(buf, 'tmp_non_use_code', columns=('nonusecode',), sep=',')

# 5) (Opcional) Verifica filas cargadas en la temp
cur.execute("SELECT COUNT(*) FROM tmp_non_use_code;")
print("Filas en tmp_non_use_code:", cur.fetchone()[0])

# 6) Upsert sencillo evitando duplicados
cur.execute("""
    INSERT INTO d_non_use_code (nonusecode)
    SELECT DISTINCT nonusecode
    FROM tmp_non_use_code
    WHERE nonusecode IS NOT NULL AND nonusecode <> ''
    ON CONFLICT (nonusecode) DO NOTHING;
""")

conn.commit()

cur.execute("SELECT COUNT(*) FROM d_non_use_code;")
print("Filas en d_non_use_code:", cur.fetchone()[0])

Filas en tmp_non_use_code: 75
Filas en d_non_use_code: 75

## DIM PROPERTY

In [ ]:
import io

# 1) Datos únicos con las columnas esperadas
df = property_dim.select([
    "address",
    "town",
    "propertytype",
    "residentialtype",
    "latitude",
    "longitude"
]).unique()

# 2) Crear tabla destino si no existe
cur.execute("""
    CREATE TABLE IF NOT EXISTS d_property(
        property_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        address TEXT NOT NULL,
        town_id BIGINT NOT NULL,
        propertytype TEXT,
        residentialtype TEXT,
        latitude DOUBLE PRECISION,
        longitude DOUBLE PRECISION,
        CONSTRAINT uq_property UNIQUE (address, town_id)
        -- Opcional (recomendado si ya tienes d_town estable):
        -- , CONSTRAINT fk_property_town FOREIGN KEY (town_id) REFERENCES d_town(town_id)
    );
""")

# 3) Temp table de staging
cur.execute("DROP TABLE IF EXISTS tmp_property;")
cur.execute("""
    CREATE TEMP TABLE tmp_property (
        address TEXT,
        town TEXT,
        propertytype TEXT,
        residentialtype TEXT,
        latitude DOUBLE PRECISION,
        longitude DOUBLE PRECISION
    ) ON COMMIT DROP;
""")

# 4) CSV en memoria (sin header) y COPY con psycopg2
buf = io.StringIO()
df.write_csv(buf, include_header=False)
buf.seek(0)
cur.copy_expert(
    "COPY tmp_property (address, town, propertytype, residentialtype, latitude, longitude) FROM STDIN WITH (FORMAT CSV)",
    buf
)

# (Opcional) Verificar carga en temp
cur.execute("SELECT COUNT(*) FROM tmp_property;")
print("Filas en tmp_property:", cur.fetchone()[0])

# 5) Asegurar towns en d_town (pre-carga para evitar nulls en el join)
cur.execute("""
    INSERT INTO d_town (town)
    SELECT DISTINCT town
    FROM tmp_property
    WHERE town IS NOT NULL AND town <> ''
    ON CONFLICT (town) DO NOTHING;
""")

# 6) Insert a d_property resolviendo town_id
cur.execute("""
    INSERT INTO d_property (address, town_id, propertytype, residentialtype, latitude, longitude)
    SELECT 
        p.address,
        t.town_id,
        p.propertytype,
        p.residentialtype,
        p.latitude,
        p.longitude
    FROM tmp_property p
    JOIN d_town t
      ON t.town = p.town
    ON CONFLICT (address, town_id) DO NOTHING;
""")

conn.commit()

cur.execute("SELECT COUNT(*) FROM d_property;")
print("Filas en d_property:", cur.fetchone()[0])

Filas en tmp_property: 982574
Filas en d_property: 851330

## d_sale_notes

In [ ]:
import io

df = sale_notes.select([
    "serialnumber",
    "remarks",
    "opm_remarks"
]).unique()

buf = io.StringIO()
df.write_csv(buf, include_header=False)  # Polars ya mete comillas si hay comas
buf.seek(0)

cur.execute("""
    CREATE TABLE IF NOT EXISTS d_sale_notes (
        note_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        serialnumber TEXT,
        remarks TEXT,
        opm_remarks TEXT
    );
""")

cur.execute("DROP TABLE IF EXISTS tmp_sale_notes;")
cur.execute("""
    CREATE TEMP TABLE tmp_sale_notes (
        serialnumber TEXT,
        remarks TEXT,
        opm_remarks TEXT
    ) ON COMMIT DROP;
""")


cur.copy_expert(
    "COPY tmp_sale_notes (serialnumber, remarks, opm_remarks) FROM STDIN WITH (FORMAT CSV)",
    buf
)

cur.execute("""
    INSERT INTO d_sale_notes (serialnumber, remarks, opm_remarks)
    SELECT DISTINCT
        serialnumber,
        remarks,
        opm_remarks
    FROM tmp_sale_notes
    WHERE serialnumber IS NOT NULL AND serialnumber <> '';
""")

conn.commit()

cur.execute("SELECT COUNT(*) FROM d_sale_notes;")
print("Filas en d_sale_notes:", cur.fetchone()[0])

Filas en d_sale_notes: 282838

## fact Sales

In [95]:
import io

# 1) Dataframe fuente (únicos)
df = sales_fact.select([
    "serialnumber",
    "listyear",
    "daterecorded",
    "assessedvalue",
    "saleamount",
    "salesratio",
    "town",
    "address",
    "propertytype",
    "residentialtype",
    "latitude",
    "longitude",
    "nonusecode"
]).unique()

# 2) CSV en memoria (sin header)
buf = io.StringIO()
df.write_csv(buf, include_header=False)
buf.seek(0)

# 3) Tabla destino si no existe
cur.execute("""
    CREATE TABLE IF NOT EXISTS f_sales (
        sale_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        serialnumber TEXT,
        listyear INT,
        daterecorded DATE,
        assessedvalue DOUBLE PRECISION,
        saleamount DOUBLE PRECISION,
        salesratio DOUBLE PRECISION,
        property_id BIGINT,
        nonusecode_id BIGINT
    );
""")

# 4) Temp table de staging
cur.execute("DROP TABLE IF EXISTS tmp_f_sales;")
cur.execute("""
    CREATE TEMP TABLE tmp_f_sales (
        serialnumber TEXT,
        listyear INT,
        daterecorded TEXT,
        assessedvalue TEXT,
        saleamount TEXT,
        salesratio TEXT,
        town TEXT,
        address TEXT,
        propertytype TEXT,
        residentialtype TEXT,
        latitude DOUBLE PRECISION,
        longitude DOUBLE PRECISION,
        nonusecode TEXT
    ) ON COMMIT DROP;
""")

# 5) COPY respetando formato CSV (comillas y comas dentro de texto)
cur.copy_expert("""
    COPY tmp_f_sales (
        serialnumber, listyear, daterecorded, assessedvalue, saleamount, salesratio,
        town, address, propertytype, residentialtype, latitude, longitude, nonusecode
    )
    FROM STDIN WITH (FORMAT CSV)
""", buf)

# (Opcional) Verifica carga
cur.execute("SELECT COUNT(*) FROM tmp_f_sales;")
print("Filas en tmp_f_sales:", cur.fetchone()[0])

# 6) Upsert de towns y properties por si llegan nuevas combinaciones (similar a tus dims)
#    (Si ya garantizas que d_town y d_property están completos, puedes omitir estas dos inserciones.)
cur.execute("""
    INSERT INTO d_town (town)
    SELECT DISTINCT town
    FROM tmp_f_sales
    WHERE town IS NOT NULL AND town <> ''
    ON CONFLICT (town) DO NOTHING;
""")

cur.execute("""
    INSERT INTO d_property (address, town_id, propertytype, residentialtype, latitude, longitude)
    SELECT DISTINCT
        p.address,
        t.town_id,
        p.propertytype,
        p.residentialtype,
        p.latitude,
        p.longitude
    FROM (
        SELECT DISTINCT address, town, propertytype, residentialtype, latitude, longitude
        FROM tmp_f_sales
        WHERE address IS NOT NULL AND address <> ''
          AND town IS NOT NULL AND town <> ''
    ) p
    JOIN d_town t
      ON t.town = p.town
    ON CONFLICT (address, town_id) DO NOTHING;
""")

cur.execute("""
    INSERT INTO f_sales (
        serialnumber, listyear, daterecorded, assessedvalue, saleamount, salesratio,
        property_id, nonusecode_id
    )
    SELECT
        s.serialnumber,
        s.listyear,
        s.daterecorded::date,
        NULLIF(s.assessedvalue, '')::double precision,
        NULLIF(s.saleamount, '')::double precision,
        NULLIF(s.salesratio, '')::double precision,
        dp.property_id,
        nuc.nonusecode_id
    FROM tmp_f_sales s
    JOIN d_town t
      ON t.town = s.town
    JOIN d_property dp
      ON dp.address = s.address
     AND dp.town_id = t.town_id
    LEFT JOIN d_non_use_code nuc
      ON nuc.nonusecode = s.nonusecode;
""")

conn.commit()

cur.execute("SELECT COUNT(*) FROM f_sales;")
print("Filas en f_sales:", cur.fetchone()[0])

Filas en tmp_f_sales: 1141722
Filas en f_sales: 1141722

ML Table

In [ ]:
cur.execute("""
    CREATE TABLE IF NOT EXISTS ML_Table (
        sale_id        BIGINT PRIMARY KEY,
        serialnumber   TEXT,
        listyear       INT,
        daterecorded   DATE,
        assessedvalue  DOUBLE PRECISION,
        saleamount     DOUBLE PRECISION,
        salesratio     DOUBLE PRECISION,
        address        TEXT,
        propertytype   TEXT,
        residentialtype TEXT,
        latitude       DOUBLE PRECISION,
        longitude      DOUBLE PRECISION,
        town           TEXT,
        nonusecode     TEXT,
        remarks_all    TEXT,
        opm_remarks_all TEXT
    );
""")


cur.execute ( """
WITH notes AS (
  SELECT
    serialnumber,
    STRING_AGG(remarks, ' | ' ORDER BY note_id)      AS remarks_all,
    STRING_AGG(opm_remarks, ' | ' ORDER BY note_id)  AS opm_remarks_all
  FROM d_sale_notes
  GROUP BY serialnumber
)
INSERT INTO ML_Table (
  sale_id,
  serialnumber,
  listyear,
  daterecorded,
  assessedvalue,
  saleamount,
  salesratio,
  address,
  propertytype,
  residentialtype,
  latitude,
  longitude,
  town,
  nonusecode,
  remarks_all,
  opm_remarks_all
)
SELECT
  f.sale_id,
  f.serialnumber,
  f.listyear,
  f.daterecorded,
  f.assessedvalue,
  f.saleamount,
  f.salesratio,
  p.address,
  p.propertytype,
  p.residentialtype,
  p.latitude,
  p.longitude,
  t.town,
  n.nonusecode,
  notes.remarks_all,
  notes.opm_remarks_all
FROM f_sales AS f
JOIN d_property AS p
  ON p.property_id = f.property_id
JOIN d_town AS t
  ON t.town_id = p.town_id
LEFT JOIN d_non_use_code AS n
  ON n.nonusecode_id = f.nonusecode_id
LEFT JOIN notes
  ON notes.serialnumber = f.serialnumber;
""" )

conn.commit()
cur.execute("SELECT COUNT(*) FROM ML_Table;")
print("Filas en ML_Table:", cur.fetchone()[0])

Se añaden Constrains

In [96]:
try:
    with conn.cursor() as cur:
        # d_property -> d_town
        cur.execute("""
            ALTER TABLE d_property
            ADD CONSTRAINT fk_property_town
            FOREIGN KEY (town_id) REFERENCES d_town(town_id);
        """)

        # f_sales -> d_property
        cur.execute("""
            ALTER TABLE f_sales
            ADD CONSTRAINT fk_sales_property
            FOREIGN KEY (property_id) REFERENCES d_property(property_id);
        """)

        # f_sales -> d_non_use_code
        cur.execute("""
            ALTER TABLE f_sales
            ADD CONSTRAINT fk_sales_nonusecode
            FOREIGN KEY (nonusecode_id) REFERENCES d_non_use_code(nonusecode_id);
        """)
except Exception as e:
    print("Error creando FKs:", e)
else:
    conn.commit()
    print("FKs creadas")

FKs creadas

In [97]:
conn.close()