Extraccion de USA RE a Mongo

In [37]:
import pandas as pd
import polars as pl
import time
import requests
from pymongo import MongoClient
from pprint import pprint
import psycopg
from pathlib import Path

ModuleNotFoundError: No module named 'psycopg'

In [ ]:

API = "https://data.ct.gov/resource/5mzw-sjtu.json"
CHUNK = 50000

client = MongoClient("mongodb+srv://RealEstateMan:Nb2rf5qwI0df9c6V@realestatecluster.cqx7s32.mongodb.net/?appName=RealEstateCluster")
col = client.RealState.realestate_raw

offset = 0
#alkdflkajdsfjasdfjaklsdfj
while True:
    params = {"$limit": CHUNK, "$offset": offset}
    r = requests.get(API, params=params, timeout=60)
    r.raise_for_status()
    rows = r.json()

    #Cuando ya no hya mas datos
    if len(rows) == 0:
        break
    
    col.insert_many(rows)

    offset += CHUNK
    time.sleep(0.2)

print("Total documentos(rows):", col.count_documents({}))

Total documentos(rows): 1141722

# Conexión Mongos y descarga de Datos

In [4]:
from pymongo import MongoClient

uri = "mongodb+srv://RealEstateMan:Nb2rf5qwI0df9c6V@realestatecluster.cqx7s32.mongodb.net/?appName=RealEstateCluster"
client = MongoClient(uri)
col = client["RealState"]["realestate_raw"]

print("OK. docs:", col.count_documents({}))

OK. docs: 1141722

In [ ]:
def load_data():
    df = pd.DataFrame(list(col.find()))
    df['_id'] = df['_id'].astype(str)
    pl_df = pl.from_pandas(df)
    return pl_df

In [6]:
pl_df = load_data()

# Transformación básica de variables

Transformaciones

1. Eliminar Columnas
2. Conversion a int y float
3. Datarecorded a fechas
4. Long Lat a coordinadas
5. Strip chars de valores

In [7]:
# Inspección rápida de pl_df
print("=" * 50)
print("INSPECCIÓN RÁPIDA DEL DATAFRAME")
print("=" * 50)
print(f"\nForma: {pl_df.shape} (filas, columnas)")
print(f"\nColumnas: {pl_df.columns}")
print(f"\nEsquema (tipos):")
print(pl_df.schema)
print(f"\nPrimeras 5 filas:")
print(pl_df.head())
print(f"\nEstadísticas básicas:")
print(pl_df.describe())

==================================================
INSPECCIÓN RÁPIDA DEL DATAFRAME
==================================================

Forma: (1141722, 19) (filas, columnas)

Columnas: ['_id', 'serialnumber', 'listyear', 'daterecorded', 'town', 'address', 'assessedvalue', 'saleamount', 'salesratio', 'propertytype', 'residentialtype', 'geo_coordinates', ':@computed_region_dam5_q64j', ':@computed_region_nhmp_cq6b', ':@computed_region_m4y2_whse', ':@computed_region_snd5_k6zv', 'remarks', 'nonusecode', 'opm_remarks']

Esquema (tipos):
Schema({'_id': String, 'serialnumber': String, 'listyear': String, 'daterecorded': String, 'town': String, 'address': String, 'assessedvalue': String, 'saleamount': String, 'salesratio': String, 'propertytype': String, 'residentialtype': String, 'geo_coordinates': Struct({'coordinates': List(Float64), 'type': String}), ':@computed_region_dam5_q64j': String, ':@computed_region_nhmp_cq6b': String, ':@computed_region_m4y2_whse': String, ':@computed_region_snd5_k6zv': String, 'remarks': String, 'nonusecode': String, 'opm_remarks': String})

Primeras 5 filas:
shape: (5, 19)
┌────────────┬────────────┬──────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ _id        ┆ serialnumb ┆ listyear ┆ daterecor ┆ … ┆ :@compute ┆ remarks ┆ nonusecod ┆ opm_remar │
│ ---        ┆ er         ┆ ---      ┆ ded       ┆   ┆ d_region_ ┆ ---     ┆ e         ┆ ks        │
│ str        ┆ ---        ┆ str      ┆ ---       ┆   ┆ snd5_k6zv ┆ str     ┆ ---       ┆ ---       │
│            ┆ str        ┆          ┆ str       ┆   ┆ ---       ┆         ┆ str       ┆ str       │
│            ┆            ┆          ┆           ┆   ┆ str       ┆         ┆           ┆           │
╞════════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ 698f65aabb ┆ 2020177    ┆ 2020     ┆ 2021-04-1 ┆ … ┆ 4         ┆ null    ┆ null      ┆ null      │
│ 4a7e47c78a ┆            ┆          ┆ 4T00:00:0 ┆   ┆           ┆         ┆           ┆           │
│ 2035       ┆            ┆          ┆ 0.000     ┆   ┆           ┆         ┆           ┆           │
│ 698f65aabb ┆ 2020225    ┆ 2020     ┆ 2021-05-2 ┆ … ┆ null      ┆ null    ┆ null      ┆ null      │
│ 4a7e47c78a ┆            ┆          ┆ 6T00:00:0 ┆   ┆           ┆         ┆           ┆           │
│ 2036       ┆            ┆          ┆ 0.000     ┆   ┆           ┆         ┆           ┆           │
│ 698f65aabb ┆ 2020348    ┆ 2020     ┆ 2021-09-1 ┆ … ┆ null      ┆ null    ┆ null      ┆ null      │
│ 4a7e47c78a ┆            ┆          ┆ 3T00:00:0 ┆   ┆           ┆         ┆           ┆           │
│ 2037       ┆            ┆          ┆ 0.000     ┆   ┆           ┆         ┆           ┆           │
│ 698f65aabb ┆ 2020090    ┆ 2020     ┆ 2020-12-1 ┆ … ┆ null      ┆ null    ┆ null      ┆ null      │
│ 4a7e47c78a ┆            ┆          ┆ 4T00:00:0 ┆   ┆           ┆         ┆           ┆           │
│ 2038       ┆            ┆          ┆ 0.000     ┆   ┆           ┆         ┆           ┆           │
│ 698f65aabb ┆ 210288     ┆ 2021     ┆ 2022-06-2 ┆ … ┆ 1         ┆ null    ┆ null      ┆ null      │
│ 4a7e47c78a ┆            ┆          ┆ 0T00:00:0 ┆   ┆           ┆         ┆           ┆           │
│ 2039       ┆            ┆          ┆ 0.000     ┆   ┆           ┆         ┆           ┆           │
└────────────┴────────────┴──────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

Estadísticas básicas:
shape: (9, 20)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ _id       ┆ serialnum ┆ listyear ┆ … ┆ :@compute ┆ remarks   ┆ nonusecod ┆ opm_remar │
│ ---       ┆ ---       ┆ ber       ┆ ---      ┆   ┆ d_region_ ┆ ---       ┆ e         ┆ ks        │
│ str       ┆ str       ┆ ---       ┆ str      ┆   ┆ snd5_k6zv ┆ str       ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆          ┆   ┆ ---       ┆           ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆ str       ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 1141722   ┆ 1141722   ┆ 1141722  ┆ … ┆ 340256    ┆ 181098    ┆ 324807    ┆ 14346     │
│ null_coun ┆ 0         ┆ 0         ┆ 0        ┆ … ┆ 801466    ┆ 960624    ┆ 816915    ┆ 1127376   │
│ t         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ std       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ min       ┆ 698f65aab ┆ 0         ┆ 2001     ┆ … ┆ 1         ┆ "AS IS    ┆ 01 -      ┆ #190309   │
│           ┆ b4a7e47c7 ┆           ┆          ┆   ┆           ┆ SALE"     ┆ Family    ┆ HAS SAME  │
│           ┆ 8a2035    ┆           ┆          ┆   ┆           ┆           ┆           ┆ REMARK    │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ AND IS…   │
│ 25%       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ max       ┆ 698f67d9b ┆ 99529     ┆ 2023     ┆ … ┆ 9         ┆ �non-mark ┆ Single    ┆ town site │
│           ┆ b4a7e47c7 ┆           ┆          ┆   ┆           ┆ et transa ┆ Family    ┆ shows ass │
│           ┆ 9b8c0e    ┆           ┆          ┆   ┆           ┆ ction     ┆           ┆ essment   │
│           ┆           ┆           ┆          ┆   ┆           ┆ includ…   ┆           ┆ as …      │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
# Eliminar columnas específicas
columnas_a_eliminar = [
    ':@computed_region_dam5_q64j',
    ':@computed_region_nhmp_cq6b',
    ':@computed_region_m4y2_whse',
    ':@computed_region_snd5_k6zv'
]

# Eliminar las columnas
pl_df = pl_df.drop(columnas_a_eliminar)

print(f"Columnas eliminadas: {columnas_a_eliminar}")
print(f"\nDataFrame después de eliminar:")
print(f"Forma: {pl_df.shape}")
print(f"Columnas restantes ({len(pl_df.columns)})")

Columnas eliminadas: [':@computed_region_dam5_q64j', ':@computed_region_nhmp_cq6b', ':@computed_region_m4y2_whse', ':@computed_region_snd5_k6zv']

DataFrame después de eliminar:
Forma: (1141722, 15)
Columnas restantes (15)

In [10]:
# copia de pl_df a una limpia que se llame pl_clean
pl_clean = pl_df.clone()

In [11]:
# Conversiones obligatorias con Polars
pl_clean = pl_clean.with_columns([
    # Numéricos
    pl.col("listyear").cast(pl.Int64, strict=False),
    pl.col("assessedvalue").cast(pl.Float64, strict=False),
    pl.col("saleamount").cast(pl.Float64, strict=False),
    pl.col("salesratio").cast(pl.Float64, strict=False),
])

In [14]:
# inspeccionar daterecord para saber su formato
print("Ejemplo de daterecorded:")
print(pl_clean.select(pl.col("daterecorded")).head(10))

Ejemplo de daterecorded:
shape: (10, 1)
┌─────────────────────────┐
│ daterecorded            │
│ ---                     │
│ str                     │
╞═════════════════════════╡
│ 2021-04-14T00:00:00.000 │
│ 2021-05-26T00:00:00.000 │
│ 2021-09-13T00:00:00.000 │
│ 2020-12-14T00:00:00.000 │
│ 2022-06-20T00:00:00.000 │
│ 2021-09-07T00:00:00.000 │
│ 2020-12-15T00:00:00.000 │
│ 2021-06-01T00:00:00.000 │
│ 2021-01-25T00:00:00.000 │
│ 2020-11-13T00:00:00.000 │
└─────────────────────────┘

In [15]:
# conversion de daterecorded a formato fecha 
pl_clean = pl_clean.with_columns(
    pl.col("daterecorded")
      .str.strptime(pl.Datetime, strict=False)
      .dt.date()
      .alias("daterecorded")
)

In [19]:
# convertimos latitud y longitud
pl_clean = (
    pl_clean
    .with_columns([
        pl.col("geo_coordinates")
          .struct.field("coordinates")
          .list.get(0)
          .alias("longitude"),

        pl.col("geo_coordinates")
          .struct.field("coordinates")
          .list.get(1)
          .alias("latitude"),
    ])
    .drop("geo_coordinates")
)

In [21]:
#limpieza de datos categoricos
pl_clean = pl_clean.with_columns([
    pl.col("town")
      .str.strip_chars()
      .str.to_uppercase(),

    pl.col("address")
      .str.strip_chars()
      .str.to_uppercase(),

    pl.col("propertytype")
      .str.strip_chars(),

    pl.col("residentialtype")
      .str.strip_chars(),
])

# Normalización

In [25]:
pl_tablas = pl_clean.clone()

## Decisión de modelado: generación de claves y relaciones en la base de datos

En este proyecto se adopta una arquitectura donde el proceso ETL (realizado en Polars) se encarga exclusivamente de la limpieza, transformación y estructuración lógica de los datos, mientras que la definición formal del modelo relacional (claves primarias, claves foráneas y restricciones de integridad) se delega al sistema gestor de base de datos (por ejemplo, PostgreSQL).

**Esta decisión responde a varias buenas prácticas en ingeniería de datos:**

- Separación de responsabilidades:
El ETL prepara datos consistentes y normalizados; el motor relacional garantiza integridad referencial y reglas de negocio mediante constraints.

- Portabilidad y flexibilidad:
Al no generar claves surrogate en la capa de transformación, el pipeline permanece independiente del motor de base de datos. Esto facilita migraciones futuras (Postgres, MySQL, SQLite, etc.).

- Integridad referencial formal:
Los sistemas relacionales están diseñados para gestionar claves primarias (PK), claves foráneas (FK), índices y validaciones de forma robusta y eficiente.

- Mantenimiento y escalabilidad:
Delegar la generación de IDs (IDENTITY / SERIAL / AUTOINCREMENT) al motor evita dependencias en el orden de carga o en la estabilidad del dataset.

Por lo tanto, en esta etapa se construyen las tablas dimensionales y de hechos con sus atributos limpios y normalizados, dejando la definición de relaciones y restricciones para la fase de carga en la base de datos relacional.

### Dimensions

### Tabla TOWN

In [26]:
town_dim = (
    pl_tablas
    .select(
        pl.col("town").fill_null("UNKNOWN")
    )
    .unique()
    .sort("town")
)
town_dim

shape: (170, 1)
┌───────────────┐
│ town          │
│ ---           │
│ str           │
╞═══════════════╡
│ ***UNKNOWN*** │
│ ANDOVER       │
│ ANSONIA       │
│ ASHFORD       │
│ AVON          │
│ …             │
│ WINDSOR LOCKS │
│ WOLCOTT       │
│ WOODBRIDGE    │
│ WOODBURY      │
│ WOODSTOCK     │
└───────────────┘

### Tabla Property

In [27]:
property_dim = (
    pl_tablas
    .select([
        pl.col("town"),
        pl.col("address").fill_null("UNKNOWN"),
        pl.col("propertytype").fill_null("UNKNOWN"),
        pl.col("residentialtype").fill_null("UNKNOWN"),
        pl.col("latitude"),
        pl.col("longitude"),
    ])
    .unique()
    .sort(["town", "address"])
)


pprint(property_dim.schema)

Schema([('town', String),
        ('address', String),
        ('propertytype', String),
        ('residentialtype', String),
        ('latitude', Float64),
        ('longitude', Float64)])

### NO_USE_CODE

Non usable sale code typically means the sale price is not reliable for use in the determination of a property value. See attachments in the dataset description page for a listing of codes

In [28]:
non_use_code_dim = (
    pl_tablas
    .select(
        pl.col("nonusecode")
          .fill_null("UNKNOWN")
    )
    .unique()
    .sort("nonusecode")
)

non_use_code_dim.unique()

shape: (75, 1)
┌─────────────────────────┐
│ nonusecode              │
│ ---                     │
│ str                     │
╞═════════════════════════╡
│ 01 - Family             │
│ 02 - Love and Affection │
│ 03 - Inter Corporation  │
│ 04 - Correcting Deed    │
│ 05 - Deed Date          │
│ …                       │
│ 8                       │
│ 88                      │
│ 9                       │
│ Single Family           │
│ UNKNOWN                 │
└─────────────────────────┘

### Sale_notes

In [30]:
sale_notes = (
    pl_tablas
    .select([
        pl.col("serialnumber"),
        pl.col("remarks").fill_null("UNKNOWN"),
        pl.col("opm_remarks").fill_null("UNKNOWN"),
    ]))
  

sale_notes.schema

Schema([('serialnumber', String),
        ('remarks', String),
        ('opm_remarks', String)])

### SALES_FACT - TABLA DE HECHOS

Uso de variables “puente” en la fact table (justificación).
Para construir las relaciones entre SALES y las dimensiones (PROPERTY_DIM, TOWN, etc.) existen dos enfoques comunes: (1) crear una clave natural/hashy (por ejemplo property_key) para enlazar tablas con una sola columna, o (2) mantener en la fact los atributos necesarios como variables puente y resolver las claves sustitutas (surrogate keys) en la base relacional mediante joins multi-columna.

En este proyecto se elige el enfoque de variables puente porque el dataset contiene una proporción alta de valores faltantes que se estandarizan como "UNKNOWN". En este contexto, una clave hash basada en atributos puede introducir colisiones lógicas (distintas propiedades terminan compartiendo la misma combinación de atributos debido a campos "UNKNOWN" o coordenadas ausentes), provocando enlaces incorrectos entre la fact y la dimensión.

Mantener los atributos puente en la fact permite realizar la resolución de property_id en SQL de forma explícita, auditable y controlable, aplicando reglas adicionales si es necesario (por ejemplo, priorizar address cuando existe, tratar casos con lat/lon nulos, o separar registros con demasiados "UNKNOWN"). Además, este enfoque mantiene el ETL más agnóstico del motor de base de datos, dejando la generación de claves sustitutas y la integridad referencial para la capa relacional.

In [31]:
sales_fact = (
    pl_tablas
    .select([
        pl.col("serialnumber"),

        pl.col("listyear"),
        pl.col("daterecorded"),  
        pl.col("assessedvalue"),
        pl.col("saleamount"),
        pl.col("salesratio"),

        # Puente para resolver property_id en la DB (porque property_dim no lleva nonusecode)
        pl.col("town").fill_null("UNKNOWN"),
        pl.col("address").fill_null("UNKNOWN"),
        pl.col("propertytype").fill_null("UNKNOWN"),
        pl.col("residentialtype").fill_null("UNKNOWN"),
        pl.col("latitude"),
        pl.col("longitude"),

        # Puente para resolver nonusecode_id en la DB
        pl.col("nonusecode"),
    ])
)

sales_fact.schema

Schema([('serialnumber', String),
        ('listyear', Int64),
        ('daterecorded', Date),
        ('assessedvalue', Float64),
        ('saleamount', Float64),
        ('salesratio', Float64),
        ('town', String),
        ('address', String),
        ('propertytype', String),
        ('residentialtype', String),
        ('latitude', Float64),
        ('longitude', Float64),
        ('nonusecode', String)])

# LOAD

# CARGA A POSTGRES

## Conexión

In [ ]:


CONN_URI = "postgresql://postgres:postgres@localhost:5432/realestate"
conn = psycopg.connect(CONN_URI)
conn.autocommit = True

print("Conectado a:", CONN_URI)

CREACION DE TABLAS

In [ ]:
with conn.cursor() as cur:
    cur.execute("""
        CREATE TABLE IF NOT EXISTS stg_town_dim (town text);

        CREATE TABLE IF NOT EXISTS stg_non_use_code_dim (nonusecode text);

        CREATE TABLE IF NOT EXISTS stg_property_dim (
            town text,
            address text,
            propertytype text,
            residentialtype text,
            latitude double precision,
            longitude double precision
        );

        CREATE TABLE IF NOT EXISTS stg_sale_notes (
            serialnumber text,
            remarks text,
            opm_remarks text
        );

        CREATE TABLE IF NOT EXISTS stg_sales_fact (
            serialnumber text,
            listyear int,
            daterecorded text,
            assessedvalue double precision,
            saleamount double precision,
            salesratio double precision,
            town text,
            address text,
            propertytype text,
            residentialtype text,
            latitude double precision,
            longitude double precision,
            nonusecode text
        );
    """)

print("Staging tables listas")

Load a Tablas

In [ ]:
# ============================================================
# PASO 3 — Poblar dimensiones base (town y nonusecode)
# ============================================================

with conn.cursor() as cur:
    cur.execute("""
        INSERT INTO town_final (town)
        SELECT DISTINCT town FROM stg_town_dim;

        INSERT INTO non_use_code_final (nonusecode)
        SELECT DISTINCT nonusecode FROM stg_non_use_code_dim;
    """)

print("✅ Paso 3 OK: town_final y non_use_code_final pobladas")

In [ ]:
# ============================================================
# PASO 4 — Poblar property_dim_final con grano correcto (address + town_id)
#   - Agrega atributos con MAX() para quedarte con un valor representativo
# ============================================================

with conn.cursor() as cur:
    cur.execute("""
        INSERT INTO property_dim_final (
            address, town_id, propertytype, residentialtype, latitude, longitude
        )
        SELECT
            p.address,
            t.town_id,
            MAX(p.propertytype),
            MAX(p.residentialtype),
            MAX(p.latitude),
            MAX(p.longitude)
        FROM stg_property_dim p
        JOIN town_final t
            ON p.town = t.town
        GROUP BY p.address, t.town_id;
    """)

print("✅ Paso 4 OK: property_dim_final poblada")

In [ ]:
# ============================================================
# PASO 5 — Poblar sales (LEFT JOIN permisivo para NO perder filas)
#   - Normaliza texto con TRIM+UPPER para evitar fallos por espacios/case
# ============================================================

with conn.cursor() as cur:
    cur.execute("TRUNCATE sales;")
    cur.execute("""
        INSERT INTO sales (
            serialnumber, listyear, daterecorded,
            assessedvalue, saleamount, salesratio,
            property_id, nonusecode_id
        )
        SELECT
            s.serialnumber,
            s.listyear,
            s.daterecorded::date,
            s.assessedvalue,
            s.saleamount,
            s.salesratio,
            p.property_id,
            n.nonusecode_id
        FROM stg_sales_fact s
        LEFT JOIN town_final t
            ON TRIM(UPPER(s.town)) = TRIM(UPPER(t.town))
        LEFT JOIN property_dim_final p
            ON TRIM(UPPER(p.address)) = TRIM(UPPER(s.address))
           AND p.town_id = t.town_id
        LEFT JOIN non_use_code_final n
            ON TRIM(UPPER(s.nonusecode)) = TRIM(UPPER(n.nonusecode));
    """)

print("✅ Paso 5 OK: sales poblada (sin perder filas)")

In [ ]:
# ============================================================
# PASO 6 — Poblar sale_notes (surrogate key note_id)
# ============================================================

with conn.cursor() as cur:
    cur.execute("TRUNCATE sale_notes;")
    cur.execute("""
        INSERT INTO sale_notes (serialnumber, remarks, opm_remarks)
        SELECT serialnumber, remarks, opm_remarks
        FROM stg_sale_notes;
    """)

print("✅ Paso 6 OK: sale_notes poblada")

In [ ]:
# ============================================================
# PASO 7 — Validación final (counts)
# ============================================================

with conn.cursor() as cur:
    cur.execute("SELECT COUNT(*) FROM town_final;")
    print("town_final:", cur.fetchone())

    cur.execute("SELECT COUNT(*) FROM non_use_code_final;")
    print("non_use_code_final:", cur.fetchone())

    cur.execute("SELECT COUNT(*) FROM property_dim_final;")
    print("property_dim_final:", cur.fetchone())

    cur.execute("SELECT COUNT(*) FROM sales;")
    print("sales:", cur.fetchone())

    cur.execute("SELECT COUNT(*) FROM sale_notes;")
    print("sale_notes:", cur.fetchone())

In [ ]:
# ============================================================
# PASO 9 — Añadir FOREIGN KEYS formales (permitiendo NULL en sales)
# ============================================================

with conn.cursor() as cur:
    # property_dim_final -> town_final
    cur.execute("""
        ALTER TABLE property_dim_final
        ADD CONSTRAINT fk_property_town
        FOREIGN KEY (town_id) REFERENCES town_final(town_id);
    """)

    # sales -> property_dim_final (NULL permitido)
    cur.execute("""
        ALTER TABLE sales
        ADD CONSTRAINT fk_sales_property
        FOREIGN KEY (property_id) REFERENCES property_dim_final(property_id);
    """)

    # sales -> non_use_code_final (NULL permitido)
    cur.execute("""
        ALTER TABLE sales
        ADD CONSTRAINT fk_sales_nonusecode
        FOREIGN KEY (nonusecode_id) REFERENCES non_use_code_final(nonusecode_id);
    """)

print("✅ Foreign keys creadas")